### ISSUE TITLE
Tests fail on Django 3

### ISSUE THREAD

**Issue by jayvdb** [magenta-aps/django_queryset_constraint#2]
```py
$ python manage.py migrate

Traceback (most recent call last):
  File "/home/travis/build/jayvdb/django_queryset_constraint/django_queryset_constraint/utils.py", line 152, in __getattribute__
    return object.__getattribute__(self, *args, **kwargs)
AttributeError: 'M' object has no attribute 'order_by'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/db/migrations/loader.py", line 206, in build_graph
    self.load_disk()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/db/migrations/loader.py", line 108, in load_disk
    migration_module = import_module(migration_path)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/jayvdb/django_queryset_constraint/django_queryset_constraint/migrations/0001_initial.py", line 12, in <module>
    class Migration(migrations.Migration):
  File "/home/travis/build/jayvdb/django_queryset_constraint/django_queryset_constraint/migrations/0001_initial.py", line 303, in Migration
    constraint=django_queryset_constraint.constraints.QuerysetConstraint(name='QC: Disallow age=1 via subquery with 7 subqueries', queryset=django_queryset_constraint.utils.M(operations=[{'args': ('objects',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': ('annotate',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': django.db.models.expressions.Exists(django_queryset_constraint.utils.M(operations=[{'args': ('objects',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': ('annotate',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': django.db.models.expressions.Exists(django_queryset_constraint.utils.M(operations=[{'args': ('objects',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': ('annotate',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': django.db.models.expressions.Exists(django_queryset_constraint.utils.M(operations=[{'args': ('objects',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': ('annotate',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': django.db.models.expressions.Exists(django_queryset_constraint.utils.M(operations=[{'args': ('objects',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': ('annotate',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': django.db.models.expressions.Exists(django_queryset_constraint.utils.M(operations=[{'args': ('objects',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': ('annotate',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': django.db.models.expressions.Exists(django_queryset_constraint.utils.M(operations=[{'args': ('objects',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': ('annotate',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': django.db.models.expressions.Exists(django_queryset_constraint.utils.M(operations=[{'args': ('objects',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': ('filter',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'age': 1}, 'type': '__call__'}, {'args': ('order_by',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {}, 'type': '__call__'}, {'args': ('query',), 'kwargs': {}, 'type': '__getattribute__'}]))}, 'type': '__call__'}, {'args': ('filter',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': True}, 'type': '__call__'}, {'args': ('order_by',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {}, 'type': '__call__'}, {'args': ('query',), 'kwargs': {}, 'type': '__getattribute__'}]))}, 'type': '__call__'}, {'args': ('filter',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': True}, 'type': '__call__'}, {'args': ('order_by',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {}, 'type': '__call__'}, {'args': ('query',), 'kwargs': {}, 'type': '__getattribute__'}]))}, 'type': '__call__'}, {'args': ('filter',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': True}, 'type': '__call__'}, {'args': ('order_by',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {}, 'type': '__call__'}, {'args': ('query',), 'kwargs': {}, 'type': '__getattribute__'}]))}, 'type': '__call__'}, {'args': ('filter',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': True}, 'type': '__call__'}, {'args': ('order_by',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {}, 'type': '__call__'}, {'args': ('query',), 'kwargs': {}, 'type': '__getattribute__'}]))}, 'type': '__call__'}, {'args': ('filter',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': True}, 'type': '__call__'}, {'args': ('order_by',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {}, 'type': '__call__'}, {'args': ('query',), 'kwargs': {}, 'type': '__getattribute__'}]))}, 'type': '__call__'}, {'args': ('filter',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': True}, 'type': '__call__'}, {'args': ('order_by',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {}, 'type': '__call__'}, {'args': ('query',), 'kwargs': {}, 'type': '__getattribute__'}]))}, 'type': '__call__'}, {'args': ('filter',), 'kwargs': {}, 'type': '__getattribute__'}, {'args': (), 'kwargs': {'collision': True}, 'type': '__call__'}])),
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/db/models/expressions.py", line 1081, in __init__
    queryset = queryset.order_by()
  File "/home/travis/build/jayvdb/django_queryset_constraint/django_queryset_constraint/utils.py", line 156, in __getattribute__
    return self.construct_queryset().__getattribute__(
  File "/home/travis/build/jayvdb/django_queryset_constraint/django_queryset_constraint/utils.py", line 110, in construct_queryset
    self.app_label_override or app_label_default or tlocals.app_label
AttributeError: '_thread._local' object has no attribute 'app_label'
```

**Comment by jayvdb** [comment]
Also Django 3.1 Expressions might be providing similar functionality
https://docs.djangoproject.com/en/3.1/ref/models/expressions/#django.db.models.Expression
I havent tried it yet.
